### ISSUE TITLE
Unable to add an AWS EKS cluster : Question

### ISSUE THREAD

**Issue by satyamkapoor** [pixel-point/kube-forwarder#12]
I have an EKS cluster to which I connect from my machine using kubectl , AWS CLI and AWS IAM. I think it authenticates the user using the AWS IAM in my case. 

When I try to add a resource, it detects the kubeconfig but upon clicking ADD SELECTED CLUSTERS, I receive a prompt - **_Failed to connect to arn:aws:eks:my-cluster-name platform cluster(s). Do you want to continue saving?_**

Can you please help how to resolve this?

Thanks!

**Comment by proAlexandr** [comment]
Hi @satyamkapoor 
Thank you that you use Kube Forwarder and for the bug report! I have investigated the problem some hours ago and I hope we will fix it in the next version within a week.

<details><summary>Details</summary>
1. We have to update `kubernetes-client/javascript` version to 0.10.2 in order to apply the patch for https://github.com/kubernetes-client/javascript/issues/243
2. `kubernetes-client/javascript` uses `shelljs` which has a problem with `electron`. We have to read this issue https://github.com/shelljs/shelljs/issues/480 and figure out a workaround.
</details>

**Comment by zen** [comment]
I have similar issue with GKE clusters. Looks like this problem would be very limiting for adoption, since AWS and GCP are 2 biggest platforms for managed k8s

**Comment by proAlexandr** [comment]
The issue is fixed here https://github.com/pixel-point/kube-forwarder/commit/bcfafd16cd99a92fbe1840f5bb20d39fc5cd8921. Will be released soon.

**Comment by lnikell** [comment]
@satyamkapoor we've just released new version, could you please check it?

**Comment by lnikell** [comment]
@zen also should work now with GKE as well

**Comment by satyamkapoor** [comment]
> @satyamkapoor we've just released new version, could you please check it?

Hey, Thanks for the update. Just tried to initiate working with the application and got a bummer - 

_Failed to connect to arn:aws:eks:eu-west-1:0000000000:cluster/my-cluster-name: aws: command not found. Please make sure you have installed AWS CLI. (https://docs.aws.amazon.com/cli/)

Do you want to continue saving?_
--------------------

Upon trying to add my 'docker for desktop' cluster, I get this message -
![image](https://user-images.githubusercontent.com/6293731/61637518-f7dce980-ac97-11e9-858d-9933f050dd30.png)


Am I doing something wrong?

**Comment by proAlexandr** [comment]
Hi @satyamkapoor 
> _Failed to connect to arn:aws:eks:eu-west-1:0000000000:cluster/my-cluster-name: aws: command not found. 
Do you install AWS CLI? For example `brew install awscli`.

> Upon trying to add my 'docker for desktop' cluster, I get this message
This means that something with connection went wrong. Please. make sure that you enter the right credentials and your cluster is running.

**Comment by satyamkapoor** [comment]
Hello, 

I do have AWS cli installed and configured. Upon running brew install cli, it updated things but still the same error. :( Maybe just my system's issue

**Comment by emmenko** [comment]
I'm also having this problem (version `1.3.0`).

<img width="418" alt="Screenshot 2019-07-23 at 13 59 28" src="https://user-images.githubusercontent.com/1110551/61710686-7302d600-ad52-11e9-9e20-1ba8b49abf31.png">

I do have `aws-iam-authenticator` installed:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/1110551/61710715-83b34c00-ad52-11e9-9348-e261238e3344.png">

My config looks like this:

```yaml
users:
- name: <cluster_name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - <token>
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: <account_name>
```

**Comment by emmenko** [comment]
Nvm, I managed to solve this. I need to pass the full path to the command 🙈

```yaml
command: /usr/local/bin/aws-iam-authenticator
```

**Comment by satyamkapoor** [comment]
Thanks! Works great! I'm closing the issue.
